/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FieldStudyRouteImport } from './routes/field-study'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEventsIdRouteImport } from './routes/_authenticated/admin.events.$id'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated/admin.posts.$id'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldStudyRoute = FieldStudyRouteImport.update({
  id: '/field-study',
  path: '/field-study',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEventsIdRoute =
  AuthenticatedAdminEventsIdRouteImport.update({
    id: '/admin/events/$id',
    path: '/admin/events/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/admin/posts/$id',
    path: '/admin/posts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/field-study': typeof FieldStudyRoute
  '/impact': typeof ImpactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/field-study': typeof FieldStudyRoute
  '/impact': typeof ImpactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/events': typeof EventsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/field-study': typeof FieldStudyRoute
  '/impact': typeof ImpactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/field-study'
    | '/impact'
    | '/sitemap.xml'
    | '/technology'
    | '/blog/$slug'
    | '/events/$slug'
    | '/blog/'
    | '/events/'
    | '/admin/'
    | '/admin/events/$id'
    | '/admin/posts/$id'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/field-study'
    | '/impact'
    | '/sitemap.xml'
    | '/technology'
    | '/blog/$slug'
    | '/events/$slug'
    | '/blog'
    | '/events'
    | '/admin'
    | '/admin/events/$id'
    | '/admin/posts/$id'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/field-study'
    | '/impact'
    | '/sitemap.xml'
    | '/technology'
    | '/blog/$slug'
    | '/events/$slug'
    | '/blog/'
    | '/events/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/events/$id'
    | '/_authenticated/admin/posts/$id'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FieldStudyRoute: typeof FieldStudyRoute
  ImpactRoute: typeof ImpactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TechnologyRoute: typeof TechnologyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-study': {
      id: '/field-study'
      path: '/field-study'
      fullPath: '/field-study'
      preLoaderRoute: typeof FieldStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events/$id': {
      id: '/_authenticated/admin/events/$id'
      path: '/admin/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/admin/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventsIdRoute: typeof AuthenticatedAdminEventsIdRoute
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventsIdRoute: AuthenticatedAdminEventsIdRoute,
  AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FieldStudyRoute: FieldStudyRoute,
  ImpactRoute: ImpactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TechnologyRoute: TechnologyRoute,
  BlogSlugRoute: BlogSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
